### PR TITLE
Open API Specification v3

### LINKED ISSUE #5: Open API 3
Is there any plans to add support for Open API 3.x ?

### PR DESCRIPTION
**Pull request by adambutler**
Changes library to support for Open API Specification v3.0.0

Fixes #5

### CODE REVIEW

**Comment by drewolson** [comment]
@adambutler Thanks! We'll take a look at this soon.

**Comment by adambutler** [comment]
👋 Just pinging a reminder on this PR.

I just wanted to mention I've been using this for https://github.com/Nexmo/nexmo-developer without any issues so far.

You can see an example where this is used [here](https://nexmo-developer-staging-pr-384.herokuapp.com/api/sms)

**Comment by drewolson** [comment]
I apologize for not getting around to this yet. Unfortunately, our internal usage of OpenAPI is not yet on v3, so this may be challenging to merge at this time. I'll have more time to look in-depth at this in the next few weeks.

**Comment by drewolson** [comment]
For the time being, I think we're going to have to avoid merging this. We rely on v2 of the specification internally and this would break our usage. I'll come back to this PR if / when we upgrade.

Sorry for the delay in the response!

**Comment by adambutler** [comment]
Hey @drewolson thanks for following up on this but I'd like to make a case for you reconsidering if possible.

I appreciate that you using v2 of the spec but I think when you take the namespace of something encompassing like `open_api_parser` on Rubygems.org then I think it is reasonable that open source component shouldn't be constrained by the founding author.

> We rely on v2 of the specification internally and this would break our usage. 

I've changed the version of this following Semver to `2.0.0` can you not just specify the version in your Gemfile:

```ruby
gem 'open_api_parser', '~> 1.2.1'
```

Alternatively I'd like to ask if you would be willing to do any of the following:

1. Work with me to make adding OAS3 support a non-breaking change.

2. Release the namespace to me on RubyGems. Changing this to something like `open_api_v2_parser`.

If none of these are options for you I'll likely fork the project into a seperate Gem and would welcome contirbutions if / when you've migrated to OAS3.

**Comment by why-el** [comment]
@adambutler perhaps you can release a V3 yourself by forking this project?

**Comment by adambutler** [comment]
@why-el I ended up building this project: https://github.com/nexmo/oas_parser

**Comment by why-el** [comment]
Oh yeah, I was actually looking at that right now. 👍

**Pull request closed without merging**
